#cloud-config
hostname: rpi-one
wifi:
  wlan0:
    ssid: "Cliffs of Insanity"
    password: "OscarMeyerWeiner"
ssh_pwauth: true
users:
  - name: edge
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: "$6$OscarMeyerWeiner$frDk.Q6MTps6qUZMXGoOGbP.kxdNLjDGDc.ibNE9FexlxY2YhdSIxOSx0Kzizl0zGO5L1R1Wxazzxqh5St5xK1"
runcmd:
  - echo "Raspberry Pi booted" > /home/pi/booted.txt
