network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
      optional: true
  wifis:
    wlan0:
      dhcp4: true
      access-points:
        "YourNetworkName":
          password: "YourPassword"
      optional: true
